from dataclasses import dataclass
from enum import Enum


class RefusalCode(str, Enum):
    UNSUPPORTED_CLAIM_CLASS = "UNSUPPORTED_CLAIM_CLASS"
    MISSING_LAW_VERSION = "MISSING_LAW_VERSION"
    MISSING_ACCEPTED_EPOCH = "MISSING_ACCEPTED_EPOCH"
    MISSING_AUTHORITY_OBJECT = "MISSING_AUTHORITY_OBJECT"
    MISSING_EXECUTION_RECEIPT = "MISSING_EXECUTION_RECEIPT"
    MISSING_VERIFICATION_RESULT = "MISSING_VERIFICATION_RESULT"
    MISSING_RECOGNITION_OBJECT = "MISSING_RECOGNITION_OBJECT"
    MISSING_RECOURSE_OBJECT = "MISSING_RECOURSE_OBJECT"
    HOST_ROLE_MISMATCH = "HOST_ROLE_MISMATCH"
    SOURCE_REPO_MISMATCH = "SOURCE_REPO_MISMATCH"
    PYPI_ATTESTATION_MISSING = "PYPI_ATTESTATION_MISSING"
    OBJECT_CHAIN_INCOMPLETE = "OBJECT_CHAIN_INCOMPLETE"


@dataclass(frozen=True)
class Refusal:
    code: RefusalCode
    meaning: str

    @classmethod
    def explain(cls, code: str) -> "Refusal":
        parsed = RefusalCode(code)
        return cls(parsed, f"VERIFRAX-PY refused: {parsed.value}")
